# Generated by Django 4.2.17 on 2024-12-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('organiser', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=100)),
                ('participants', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('agenda', models.TextField()),
            ],
        ),
    ]
