# Generated by Django 4.2.17 on 2024-12-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0002_remove_event_duration_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='starttime',
            field=models.TimeField(null=True),
        ),
    ]
