# Generated by Django 4.2.17 on 2024-12-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0004_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actual_endtime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='actual_starttime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
