# Generated by Django 4.2.17 on 2024-12-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0005_event_actual_endtime_event_actual_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
