# Generated by Django 4.2.17 on 2024-12-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0007_alter_event_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='remark',
            field=models.JSONField(default=list),
        ),
    ]
