# Generated by Django 4.2.17 on 2024-12-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0010_alter_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='actual_duration',
            field=models.DurationField(null=True),
        ),
    ]
