# Generated by Django 4.2.17 on 2024-12-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0011_event_actual_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=500)),
                ('priority', models.CharField(max_length=50)),
                ('assigned_date', models.DateField()),
                ('final_date', models.DateField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetingapp.event')),
            ],
        ),
    ]
