# Generated by Django 4.2.17 on 2024-12-13 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0012_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='partner',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='partner_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='meetingapp.event'),
        ),
        migrations.AlterField(
            model_name='task',
            name='person',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='remark',
            field=models.TextField(),
        ),
    ]
